name: Salesforce Code Analyzer
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install Code Analyzer Plugin
        run: sf plugins install code-analyzer

      - name: Run Code Analyzer
        run: |
          sf code-analyzer run \
            --workspace . \
            --rule-selector "pmd:Helios_Commerce_Cloud_Ruleset,eslint,flow" \
            --output-file results.sarif
        continue-on-error: true

      - name: Fix SARIF paths
        run: |
          sed -i '/"uriBaseId":/d' results.sarif
          sed -i 's/"uri": "\(.*\)",/"uri": "\1"/g' results.sarif
          sed -i 's|[^"]*/force-app/|force-app/|g' results.sarif
          

      - name: Upload SARIF file to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
          checkout_path: ${{ github.workspace }}
